const quotes = [
    "Même le plus petit des poussins peut devenir un grand coq.",
    "Ne laisse jamais personne te dire que tu ne peux pas voler haut.",
    "Un jour sans grattage de terre, c'est comme un jour sans soleil.",
    "Chaque œuf pondu est une victoire de la persévérance.",
    "Ne te contente pas de picorer, vise à explorer tout le champ.",
    "Le courage, c'est d'affronter le renard et de continuer à pondre des œufs.",
    "Quand la vie te donne des grains, fais-en un festin.",
    "Un poulet qui ne gratte pas ne trouve pas de vers.",
    "Il faut croire en soi, même quand on est juste un petit poussin.",
    "Ne te compare pas aux autres poules, chacune a son propre rythme de ponte.",
    "Chaque battement d'aile te rapproche un peu plus du sommet.",
    "Un poulailler uni est plus fort contre le renard.",
    "Les plus belles plumes viennent après la mue.",
    "Ne laisse pas la barrière du poulailler limiter tes rêves.",
    "Un poulet confiant est un poulet heureux.",
    "Chaque graine picorée est une graine de succès.",
    "Les nuages passent, mais le coq reste debout sur le toit.",
    "Ne te décourage pas si l'œuf tarde à éclore, la patience est mère de réussite.",
    "Même dans la basse-cour, il y a toujours des sommets à atteindre.",
    "Un poulet ne craint pas la pluie, car il sait que le soleil reviendra.",
    "Le véritable courage, c'est de continuer à gratter même quand la terre est dure.",
    "Un poulet déterminé peut surmonter n'importe quel obstacle.",
    "Ne perds jamais de vue le ciel, même si tes pattes touchent la terre.",
    "Chaque poule a son jour de gloire, continue de croire en toi.",
    "La confiance en soi est comme un coq qui chante à l'aube, même dans l'obscurité.",
    "Les rêves sont les ailes invisibles qui permettent de voler plus haut.",
    "Ne te laisse pas abattre par le vent, il te pousse à te renforcer.",
    "Chaque matin est une nouvelle opportunité de pondre un œuf d'or.",
    "Un poulet qui s'entraîne chaque jour devient un champion du grattage.",
    "Même si tu es une petite poule, tu peux pondre de grands œufs.",
    "Le bonheur se trouve dans chaque petit grain de maïs.",
    "Les plus grandes batailles sont gagnées une plume à la fois.",
    "L'avenir appartient à ceux qui se lèvent tôt pour picorer.",
    "Une basse-cour harmonieuse est la clé du succès.",
    "Ne te laisse pas distraire par les caquètements des autres, reste concentré sur ton objectif.",
    "Même un coq rouillé peut briller avec un peu d'effort.",
    "Chaque pas dans la boue est une avancée vers des jours ensoleillés.",
    "Ne sous-estime jamais la puissance d'un battement d'aile.",
    "Le respect se gagne en étant authentique et sincère.",
    "Un poulet qui ose explorer au-delà de la clôture découvre de nouvelles opportunités.",
    "Les plus grands voyages commencent par un petit grattage.",
    "Il n'y a pas de honte à commencer petit, l'important est de continuer à grandir.",
    "Les épreuves rendent les plumes plus résistantes.",
    "Ne laisse jamais un échec te définir, utilise-le comme tremplin.",
    "Chaque jour est une chance de réinventer ton chant du matin.",
    "Un poulailler plein de rires est un poulailler prospère.",
    "La clé du succès est de toujours picorer un peu plus chaque jour.",
    "Ne laisse pas la peur de l'échec t'empêcher de voler.",
    "Les plus belles histoires sont écrites par ceux qui osent sortir du poulailler."
];


export default quotes